# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
var_box            = 'oraclebase/oracle-8'
var_vm_name        = 'ansible_database1_vagrant'
var_ip             = "192.168.56.103"
var_mem_size       = 4096  # More would be better.
var_cpus           = 4
var_non_rotational = 'on' # SSD
var_disk1_name     = './ol8_19_u01.vdi'
var_disk2_name     = './ol8_19_u02.vdi'
var_disk_size      = 100

Vagrant.configure("2") do |config|
  config.vm.box = var_box

  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "private_network", ip: var_ip

  config.vm.provider "virtualbox" do |vb|
    vb.memory = var_mem_size
    vb.cpus   = var_cpus
    vb.name   = var_vm_name
    
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '0', '--nonrotational', var_non_rotational]

    unless File.exist?(var_disk1_name)
      vb.customize ['createhd', '--filename', var_disk1_name, '--size', var_disk_size * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--nonrotational', var_non_rotational, '--medium', var_disk1_name]

    unless File.exist?(var_disk2_name)
      vb.customize ['createhd', '--filename', var_disk2_name, '--size', var_disk_size * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--nonrotational', var_non_rotational, '--medium', var_disk2_name]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sh /vagrant/scripts/setup.sh
  SHELL
end
